version: '3.7'

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    volumes:
      - ./data-embedding:/data:Z
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=$ZINC_USER
      - ZINC_FIRST_ADMIN_PASSWORD=$ZINC_PASSWORD
    ports:
      - '4080:4080'
