version: '3.7'

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    volumes:
      - ../data-embedding:/data:Z
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=$ZINC_USER
      - ZINC_FIRST_ADMIN_PASSWORD=$ZINC_PASSWORD
    ports:
      - '4080:4080'

  server:
    image: odraxs/go-z-v-mail-server:latest
    depends_on: 
      - zincsearch
    environment:
     - ZINC_USER=$ZINC_USER
     - ZINC_PASSWORD=$ZINC_PASSWORD
    ports:
      - '3001:3001'

  web:
    image: odraxs/go-z-v-mail-web:latest
    depends_on: 
      - server
    ports:
      - '5173:5173'
