name: Project CI

on:
  push:
    branches:
      - "main"
      - "v*.[0-9]"
  pull_request:

jobs:
  web-ci:
    name: Project CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.10.x"]
        dir : ["web"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: mv .env.example .env
        working-directory: ${{ matrix.dir }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          working-directory: ${{ matrix.dir }}

      - name: Install Yarn
        run: |
              npm install -g yarn
              npm i
        working-directory: ${{ matrix.dir }}

      - name: Run lint
        run: yarn lint
        working-directory: ${{ matrix.dir }}

      - name: Run tests
        run: yarn test:unit
        working-directory: ${{ matrix.dir }}

  server-ci:
    name: Wev CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x"]
        dir: ["server", "data-embedding"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run test
        run: go test ./...
        working-directory: ${{ matrix.dir }}

      - name: Run vet
        run: go vet ./...
        working-directory: ${{ matrix.dir }}

      # This action doesn't work with go-version > 1.19 😟
      # - uses: dominikh/staticcheck-action@v1.3.0
      #   with:
      #     version: "2022.1.3"
      #     install-go: false
      #     cache-key: ${{ matrix.go-version }}
      #     working-directory: ${{ matrix.dir }}
